//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModelMyPhotos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Photos
    {
        public Photos()
        {
            this.Persons_Photo = new HashSet<Persons>();
        }
    
        public int Photo_Id { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string Event { get; set; }
        public string Landscape { get; set; }
        public string Path { get; set; }
    
        public virtual Places Places_Photo { get; set; }
        public virtual ICollection<Persons> Persons_Photo { get; set; }
    }
}
