//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModelMyPhotos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Places
    {
        public Places()
        {
            this.Photos = new HashSet<Photos>();
            this.Films = new HashSet<Films>();
        }
    
        public int Place_Id { get; set; }
        public string Country { get; set; }
        public string City { get; set; }
        public string Region { get; set; }
    
        public virtual ICollection<Photos> Photos { get; set; }
        public virtual ICollection<Films> Films { get; set; }
    }
}
